### ISSUE TITLE
Cron Jobs for cleaner code 🌱

### ISSUE THREAD

**Issue by inezabonte** [FelixWaweru/MHENGA#1]
**Hey 👋🏽 @FelixWaweru** 
- I noticed that you are using SetInterval to Tweet every 6 - 8 hours. Using Set Interval has resulted in you nesting several functions and callbacks in one whole thing which can be confusing. and messy.🙃
- A cleaner🧼 way I would suggest would be to use cron jobs to schedule tasks that run at specific times. 
Here is a [Link](https://www.npmjs.com/package/node-cron) for reference
Happy Coding 🚀

**Comment by FelixWaweru** [comment]
Thank you @inezabonte for the heads up!!

I'm still a JavaScript novice so it's great to get tips like these from the community.👍🏽
I'll definitely look into implementing the cron job in the near future.

**Comment by alphaolomi** [comment]
Start small, grow to be a baobab and more

**Comment by FelixWaweru** [comment]
Cron job implemented: #2 
First issue has been successfully closed 🎉
